Repository avinash201199/weather-app, pull requests merged in 2022-10, with the labels that each got.

#6 Week based weather update
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#10 Added Sunrise and Sunset time.
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#11 added code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest accepted

#13 Responsive Weekly Report
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#15 add full date
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#17 Added location based infos
  script.js
Labels: hacktoberfest, hacktoberfest accepted

#21 Revert "Added location based infos"
  script.js
Labels: hacktoberfest, hacktoberfest accepted

#18 Added form focus states for improved accessibility
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#19 fix to the background image repeating and more responsive
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#20 UI suggestions by matea
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#24 stop the user being allowed to submit with an empty location
  script.js
Labels: hacktoberfest, hacktoberfest accepted

#26 Added Air Quality
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#29 Interactive Future Forecast
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#34 Fix responsive and add better weather items creation.
  assets/css/bootstrap.min.css
  assets/css/style.css
  assets/js/script.js
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#36 Added hover effect to the .weather-forecast-item
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest accepted

#41 Country Search
  assets/js/Capitals.js
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#42 added city list of india
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#40 Update script.js
  assets/js/script.js
Labels: hacktoberfest, hacktoberfest accepted

#44 Corrections, please accept
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#45 Added favicon to the weather-app website
  assets/weather-icon.png
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#49 Added Responsive for more Device and add smooth transition
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest accepted

#48 Commit modify index css responsive
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#52 weather by current location
  assets/js/script.js
Labels: hacktoberfest, hacktoberfest accepted

#55 some text and code added
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#57 added toast
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#62 new search text animation
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest accepted

#70 Fixed Everything. Sorry About the Unexpected PR Close.
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest accepted

#61 Fixed some UI and improved the function formatAMPM
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#58 added the icons for the wind speed,humidity,sunrise and sunset
  assets/css/style.css
  assets/icons/humidity.png
  assets/icons/sunrise (2).png
  assets/icons/sunset (1).png
  assets/icons/wind.png
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#66 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest accepted

#75 Added a favicon
  assets/favicon.ico
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#79 UX enhancements - Improved the main weather card
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#80 centered the search bar and search icon
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#90 Changed default static city to dynamic and some minor improvements
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#84 Added main element to give screen readers a landmark region
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#98 Revert "Added main element to give screen readers a landmark region"
  index.html
Labels: hacktoberfest accepted

#86 updated font styles and forecast card look
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#93 added alt text to all images
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#95 create config module
  assets/js/script.js
  config/config.js
Labels: hacktoberfest, hacktoberfest accepted

#99 Revert "added alt text to all images"
  index.html
Labels: hacktoberfest accepted

#92 load user city's weather when they visit
  assets/js/script.js
Labels: hacktoberfest, hacktoberfest accepted

#102 To Know the Basic Weather Terminology.
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#110 feat: multi-language support
  assets/js/script.js
  index.html
  lang/translation.js
Labels: hacktoberfest, hacktoberfest accepted

#117 Auto clear search bar, Closes #107
  assets/js/script.js
Labels: hacktoberfest, hacktoberfest accepted

#119 Updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest accepted

#121 added width and height to imgs
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#114 Unit conversion feature added and hide the scrollbar for better UI
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#126 Make current day more visible
  assets/js/City.js
  assets/js/script.js
Labels: hacktoberfest, hacktoberfest accepted

#132 Adding the spanish languaje
  lang/translation.js
Labels: hacktoberfest, hacktoberfest accepted

#134 Day of Week and Timeline added
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#135 Updation in main weather card (issue #68)
  assets/css/style.css
Labels: hacktoberfest, hacktoberfest accepted

#131 Support language-based translations and add german translation
  assets/js/script.js
  lang/translation.js
Labels: hacktoberfest, hacktoberfest accepted

#133 Added Notifications
  assets/js/notification.js
  assets/js/script.js
Labels: hacktoberfest accepted

#144 footer
  assets/css/style.css
  index.html
Labels: hacktoberfest accepted

#139 Bug fix - added an div wrapper around 'img' inline element
  assets/js/script.js
  index.html
Labels: hacktoberfest accepted

#148 Make date at top of page more readable
  index.html
Labels: hacktoberfest accepted

#152 Made header and weather forecast background more legible
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest accepted

#153 dx: added sponsor link
  .Github/FUNDING.yaml
Labels: hacktoberfest accepted

#154 New feature focus input search bar: issue history - Implement focus functionality on search-bar using Js #146
  assets/js/script.js
  index.html
Labels: hacktoberfest accepted

#160 conflict is solved footer size is bit reduced
  assets/css/style.css
  assets/icons/github.png
  assets/icons/instagram.png
  assets/icons/linkedin.png
  index.html
Labels: hacktoberfest accepted

#164 Made some changes to the UI and added better font styling to the website, Issue No : #157
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest accepted

#165 Fix temperature checkbox overlap issue
  assets/css/style.css
  index.html
Labels: hacktoberfest accepted

#167 changes in footer style , issue no: 161
  assets/css/style.css
  index.html
Labels: hacktoberfest accepted

#162 Scroll Top Feature added & it was responsive for all devices
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest accepted

#170 Temp Unit Button and links in footer
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted

#171 Live clock feature -> Bug fix for issue no: 168 - Improved the Date,Time from static to Dynamic using SetInterval- Changes time for every one second
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted

#176 Fixed social media icons
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted

#181 updated
  assets/js/script.js
Labels: hacktoberfest-accepted

#188 toggle bug fixed
  assets/js/script.js
Labels: hacktoberfest-accepted

#190 dx: added features template
  .Github/ISSUE_TEMPLATE/features.yaml
  .Github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#191 Update translation.js adding french language
  lang/translation.js
Labels: hacktoberfest-accepted

#192 fix temp toggle ux
  index.html
Labels: hacktoberfest-accepted

#193 added hover effect to social icons
  assets/css/style.css
Labels: hacktoberfest-accepted

#195 hover effect
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted

#197 Implemented BEM Naming Convention in Weather App, Issue closed for 187.
  README.md
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted

#200 Closes #199
  lang/translation.js
Labels: hacktoberfest-accepted

#203 Update script.js
  assets/js/script.js
Labels: hacktoberfest-accepted

#204 Fixed grammar mistakes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#206 Add Greek , Japanese Localization
  lang/translation.js
Labels: hacktoberfest-accepted

#208 UI enhancement
  index.html
Labels: hacktoberfest-accepted

#210 Add Albanian Localization
  lang/translation.js
Labels: hacktoberfest-accepted

#213 Update index.html
  index.html
Labels: hacktoberfest-accepted

#215 Improving footer UI
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted
